name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Code checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Docker login (Secrets use)
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t shreejaadmin/flask-docker-demo:latest .

      # 4️⃣ Push Docker image
      - name: Push Docker image
        run: docker push shreejaadmin/flask-docker-demo:latest

      # 5️⃣ Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo apt update
            sudo apt install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker

            sudo docker pull shreejaadmin/flask-docker-demo:latest
            sudo docker stop flask_app || true
            sudo docker rm flask_app || true
            sudo docker run -d -p 80:80 --name flask_app shreejaadmin/flask-docker-demo:latest